[package]
name = "bevy_star_skybox"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11", features = ["exr"] }
hipparcos_catalog = { git = "ssh://git@github.com/austincummings/hipparcos_catalog.git" }
image = "0.24"

[dev-dependencies]
bevy_panorbit_camera = "0.6"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
